### ISSUE TITLE
I have error!

### ISSUE THREAD

**Issue by RedMark99** [ClipsAI/clipsai#6]
ERROR:
```
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Unity\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
C:\Users\Unity\PycharmProjects\ClipAi\.venv\Lib\site-packages\pyannote\audio\core\io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
C:\Users\Unity\PycharmProjects\ClipAi\.venv\Lib\site-packages\pyannote\audio\pipelines\speaker_verification.py:43: UserWarning: torchaudio._backend.get_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  backend = torchaudio.get_audio_backend()
C:\Users\Unity\AppData\Local\Programs\Python\Python312\Lib\inspect.py:1007: UserWarning: Module 'speechbrain.pretrained' was deprecated, redirecting to 'speechbrain.inference'. Please update your script. This is a change from SpeechBrain 1.0. See: https://github.com/speechbrain/speechbrain/releases/tag/v1.0.0
  if ismodule(module) and hasattr(module, '__file__'):
C:\Users\Unity\PycharmProjects\ClipAi\.venv\Lib\site-packages\pyannote\audio\pipelines\speaker_verification.py:45: UserWarning: Module 'speechbrain.pretrained' was deprecated, redirecting to 'speechbrain.inference'. Please update your script. This is a change from SpeechBrain 1.0. See: https://github.com/speechbrain/speechbrain/releases/tag/v1.0.0
  from speechbrain.pretrained import (
C:\Users\Unity\PycharmProjects\ClipAi\.venv\Lib\site-packages\pyannote\audio\pipelines\speaker_verification.py:53: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend(backend)
C:\Users\Unity\PycharmProjects\ClipAi\.venv\Lib\site-packages\pyannote\audio\tasks\segmentation\mixins.py:37: UserWarning: `torchaudio.backend.common.AudioMetaData` has been moved to `torchaudio.AudioMetaData`. Please update the import path.
  from torchaudio.backend.common import AudioMetaData
Traceback (most recent call last):
  File "C:\Users\Unity\PycharmProjects\ClipAi\.venv\Lib\site-packages\nltk\corpus\util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Unity\PycharmProjects\ClipAi\.venv\Lib\site-packages\nltk\data.py", line 579, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource bcp47 not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('bcp47')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/bcp47.zip/bcp47/

  Searched in:
    - 'C:\\Users\\Unity/nltk_data'
    - 'C:\\Users\\Unity\\PycharmProjects\\ClipAi\\.venv\\nltk_data'
    - 'C:\\Users\\Unity\\PycharmProjects\\ClipAi\\.venv\\share\\nltk_data'
    - 'C:\\Users\\Unity\\PycharmProjects\\ClipAi\\.venv\\lib\\nltk_data'
    - 'C:\\Users\\Unity\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Unity\PycharmProjects\ClipAi\.venv\Scripts\MakeClips.py", line 2, in <module>
    from nltk.langnames import langcode
  File "C:\Users\Unity\PycharmProjects\ClipAi\.venv\Lib\site-packages\nltk\langnames.py", line 161, in <module>
    bcp47.load_wiki_q()  # Wikidata conversion table needs to be loaded explicitly
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Unity\PycharmProjects\ClipAi\.venv\Lib\site-packages\nltk\corpus\util.py", line 120, in __getattr__
    self.__load()
  File "C:\Users\Unity\PycharmProjects\ClipAi\.venv\Lib\site-packages\nltk\corpus\util.py", line 86, in __load
    raise e
  File "C:\Users\Unity\PycharmProjects\ClipAi\.venv\Lib\site-packages\nltk\corpus\util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Unity\PycharmProjects\ClipAi\.venv\Lib\site-packages\nltk\data.py", line 579, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource bcp47 not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('bcp47')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/bcp47

  Searched in:
    - 'C:\\Users\\Unity/nltk_data'
    - 'C:\\Users\\Unity\\PycharmProjects\\ClipAi\\.venv\\nltk_data'
    - 'C:\\Users\\Unity\\PycharmProjects\\ClipAi\\.venv\\share\\nltk_data'
    - 'C:\\Users\\Unity\\PycharmProjects\\ClipAi\\.venv\\lib\\nltk_data'
    - 'C:\\Users\\Unity\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************
```

I have libarary:
```
(.venv) PS C:\Users\Unity\PycharmProjects\ClipAi> pip show clipsai
Name: clipsai
Version: 0.2.1
Summary: Clips AI is an open-source Python library that automatically converts long videos into clips
Home-page: https://clipsai.com/
Author: Benjamin Smidt, Johann Ramirez, Armel Talla
Author-email: support@clipsai.com
License: MIT
Location: C:\Users\Unity\PycharmProjects\ClipAi\.venv\Lib\site-packages
Requires: av, facenet-pytorch, matplotlib, mediapipe, nltk, numpy, opencv-python, pandas, psutil, pyannote.audio, pyannote.core, pynvml, pytest, python-magic, scenedetect, scikit-learn, scipy, sentence-transformers, torch
Required-by: 
(.venv) PS C:\Users\Unity\PycharmProjects\ClipAi> pip show libmagic
Name: libmagic
Version: 1.0
Summary: libmagic bindings
Home-page: http://bitbucket.org/xmonader/pymagic-dev
Author: Ahmed Youssef
Author-email: xmonader@gmail.com
License: GPL v3
Location: C:\Users\Unity\PycharmProjects\ClipAi\.venv\Lib\site-packages
Requires: 
Required-by: 
(.venv) PS C:\Users\Unity\PycharmProjects\ClipAi> pip show ffmpeg
Name: ffmpeg
Version: 1.4
Summary: ffmpeg python package url [https://github.com/jiashaokun/ffmpeg]
Home-page: https://github.com/jiashaokun/ffmpeg
Author: SkeyJIA
Author-email: 363604236@qq.com
License: MIT Licence
Location: C:\Users\Unity\PycharmProjects\ClipAi\.venv\Lib\site-packages
Requires:
Required-by:
```
Code:
```
from clipsai import Transcriber
from nltk.langnames import langcode

transcriber = Transcriber()
transcription = transcriber.transcribe("video.mp4", "eng")

clipfinder = ClipFinder()
clips = clipfinder.find_clips(transcription=transcription)

print("StartTime: ", clips[0].start_time)
print("EndTime: ", clips[0].end_time)
```
Please help :(

**Comment by DiMiTriFrog** [comment]
Exactly the same. 
Using Macbook pro m3.

**Comment by DiMiTriFrog** [comment]
Fixed.


Add to your code: 

```
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
```
